import React from "react"
// import ReactDOM from "react-dom"
import Game from "./containers/Game"
import "./App.css"

class App extends React.Component {
  state = {
    levelBoard: [
      [
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "lightgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey"
      ],
      [
        "darkgrey",
        "lightgrey",
        "green",
        "blue",
        "orange",
        "green",
        "orange",
        "red",
        "green",
        "blue",
        "lightgrey",
        "darkgrey"
      ],
      [
        "darkgrey",
        "lightgrey",
        "red",
        "green",
        "blue",
        "orange",
        "purple",
        "green",
        "orange",
        "purple",
        "lightgrey",
        "darkgrey"
      ],
      [
        "darkgrey",
        "lightgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "lightgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "lightgrey",
        "darkgrey"
      ],
      [
        "darkgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "darkgrey"
      ],
      [
        "darkgrey",
        "lightgrey",
        "lightgrey",
        "yellow",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "blue",
        "lightgrey",
        "darkgrey",
        "darkgrey"
      ],
      [
        "darkgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "blue",
        "darkgrey"
      ],
      [
        "darkgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "blue",
        "darkgrey"
      ],
      [
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "lightgrey",
        "darkgrey"
      ],
      [
        "darkgrey",
        "lightgrey",
        "blue",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "darkgrey"
      ],
      [
        "darkgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "lightgrey",
        "white",
        "darkgrey"
      ],

      [
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey",
        "darkgrey"
      ]
    ]
  }

  render() {
    return (
      <div>
        <Game board={this.state.levelBoard} />
      </div>
    )
  }
}

export default App
